export const ROOT = '/'
export const LOGIN = '/login'
export const FORGOT_PASSWORD = '/forgot-password'
export const CHANGE_PASSWORD = '/change-password'
export const DASHBOARD = '/dashboard'
export const SETTING = '/setting'
export const NOTIFICATION = '/notification'
